spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_machine
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/init.sql
      data-locations: classpath:/db/populate.sql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %highlight(%-5level) %cyan(%class{50}.%M:%L) - %msg%n'